### ISSUE TITLE
Add instructions to the README showing how to use the generated quay.io image

### ISSUE THREAD

**Issue by mmusgrov** [jbosstm/lra-coordinator-quarkus#50]
Issue https://issues.redhat.com/browse/JBTM-3540 includes a request to include instructions on how to use the image.

**Comment by xstefank** [comment]
Usage intructions added to https://quay.io/repository/jbosstm/lra-coordinator.

**Comment by xstefank** [comment]
Documented in https://quay.io/repository/jbosstm/lra-coordinator.
